#!/bin/bash
#SBATCH --job-name=job        # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=1        # Schedule one core
#SBATCH --time=10:00:00          # Run time (hh:mm:ss) - run for 10 hour max
#SBATCH --partition=red    # Run on either the Red or Brown queue
#hello again
# Print out the hostname of the node the job is running on
python3 LCA.py
